name: Deploy New Relic Agent to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: List Azure Resource Groups
      if: success()
      run: az group list --output table --debug

    - name: Install New Relic Agent
      run: |
        # Download and install the New Relic agent
        curl -O https://download.newrelic.com/install/newrelic-infra/agent/newrelic-infra-linux-amd64.tar.gz
        tar -xvf newrelic-infra-linux-amd64.tar.gz
        cd newrelic-infra-linux-amd64
        sudo ./newrelic-infra-ctl -l ae4f67198be65ab783366eb38e896e27FFFFNRAL --display-name test

    # Replace <YOUR_LICENSE_KEY> and <YOUR_DISPLAY_NAME> with your New Relic license key and display name.
