name: Deploy New Relic Agent to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-new-relic-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: List Azure Resource Groups
      if: success()
      run: az group list --output table --debug

    - name: Copy New Relic Agent Installer Script
      run: |
        curl -o newrelic-agent-install.sh https://download.newrelic.com/install/newrelic-agent/newrelic-cli/scripts/install.sh
        chmod +x newrelic-agent-install.sh
      continue-on-error: true

    - name: Install New Relic Agent
      run: |
        ./newrelic-agent-install.sh \
          --set license_key=${{ secrets.NEW_RELIC_LICENSE_KEY }} \
          --set display_name=<VM_DISPLAY_NAME>
      continue-on-error: true

    - name: Restart Service
      run: sudo systemctl restart newrelic-infra

    - name: Clean Up Installer Script
      run: rm -f newrelic-agent-install.sh

    - name: Check New Relic Agent Status
      run: systemctl status newrelic-infra
