name: Deploy New Relic Agent to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-newrelic-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: List Azure Resource Groups
      if: success()
      run: az group list --output table --debug

    - name: Install New Relic Infra Agent
      run: |
        # Replace with your New Relic license key and download URL
        NR_LICENSE_KEY="ae4f67198be65ab783366eb38e896e27FFFFNRAL"
        NR_AGENT_URL="curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=NRAK-WFR4FEIQIFHDG3LDLTT9BEWZVY8 NEW_RELIC_ACCOUNT_ID=4183826 /usr/local/bin/newrelic install"
        # Download and install New Relic Infra Agent
        curl -L $NR_AGENT_URL -o newrelic-infra.tar.gz
        tar xzf newrelic-infra.tar.gz
        cd newrelic-infra-linux-*
        sudo ./nri-agent -register -licenseKey=$NR_LICENSE_KEY

    - name: Restart New Relic Agent
      run: sudo systemctl restart newrelic-infra

    - name: Check New Relic Agent Status
      run: sudo systemctl status newrelic-infra
